/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AccountApi,
  AnnotationApi,
  AttributeApi,
  CancellationInsightApi,
  EventApi,
  GoalApi,
  MetricApi,
  ReasonApi,
  SegmentApi,
  SourceApi,
  UserApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BaremetricsCustom } from "./client-custom";

export class Baremetrics extends BaremetricsCustom {
  readonly account: AccountApi;
  readonly annotation: AnnotationApi;
  readonly attribute: AttributeApi;
  readonly cancellationInsight: CancellationInsightApi;
  readonly event: EventApi;
  readonly goal: GoalApi;
  readonly metric: MetricApi;
  readonly reason: ReasonApi;
  readonly segment: SegmentApi;
  readonly source: SourceApi;
  readonly user: UserApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.account = new AccountApi(configuration);
    this.annotation = new AnnotationApi(configuration);
    this.attribute = new AttributeApi(configuration);
    this.cancellationInsight = new CancellationInsightApi(configuration);
    this.event = new EventApi(configuration);
    this.goal = new GoalApi(configuration);
    this.metric = new MetricApi(configuration);
    this.reason = new ReasonApi(configuration);
    this.segment = new SegmentApi(configuration);
    this.source = new SourceApi(configuration);
    this.user = new UserApi(configuration);
  }

}
