/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AttributeSetPropertiesRequestAttributesInner
 */
export interface AttributeSetPropertiesRequestAttributesInner {
    /**
     * Supply this, or customer_email
     * @type {string}
     * @memberof AttributeSetPropertiesRequestAttributesInner
     */
    'customer_oid': string;
    /**
     * Supply this, or customer_oid
     * @type {string}
     * @memberof AttributeSetPropertiesRequestAttributesInner
     */
    'customer_email': string;
    /**
     * 
     * @type {string}
     * @memberof AttributeSetPropertiesRequestAttributesInner
     */
    'field_id': string;
    /**
     * For an array field, use a comma seperated string
     * @type {string}
     * @memberof AttributeSetPropertiesRequestAttributesInner
     */
    'value': string;
}

