/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SourceCreateSubscriptionRequestAddonsInner } from './source-create-subscription-request-addons-inner';

/**
 * 
 * @export
 * @interface SourceUpdateSubscriptionRequest
 */
export interface SourceUpdateSubscriptionRequest {
    /**
     * Your unique ID for the plan
     * @type {string}
     * @memberof SourceUpdateSubscriptionRequest
     */
    'plan_oid': string;
    /**
     * A unix timestamp of when this change occurred. Defaults to now
     * @type {string}
     * @memberof SourceUpdateSubscriptionRequest
     */
    'occurred_at'?: string;
    /**
     * In cents. The OID can be anything you want.
     * @type {Array<SourceCreateSubscriptionRequestAddonsInner>}
     * @memberof SourceUpdateSubscriptionRequest
     */
    'addons'?: Array<SourceCreateSubscriptionRequestAddonsInner>;
    /**
     * 
     * @type {number}
     * @memberof SourceUpdateSubscriptionRequest
     */
    'quantity'?: number;
    /**
     * Integer value (in the same currency as the plan)
     * @type {number}
     * @memberof SourceUpdateSubscriptionRequest
     */
    'discount'?: number;
}

