/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SourceCreateOneOffRefundRequest
 */
export interface SourceCreateOneOffRefundRequest {
    /**
     * Your unique reference for this charge
     * @type {string}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'oid': string;
    /**
     * The charge amount (in cents)
     * @type {number}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'amount': number;
    /**
     * The ISO code of the currency of this plan. E.G: usd
     * @type {string}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'currency': string;
    /**
     * Your unique ID for the customer
     * @type {string}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'customer_oid': string;
    /**
     * Which charge do you want to refund? This must be an API charge.
     * @type {string}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'charge_oid': string;
    /**
     * Unix timestamp of when this was created
     * @type {string}
     * @memberof SourceCreateOneOffRefundRequest
     */
    'created'?: string;
}

