/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SourceCreatePlanRequest
 */
export interface SourceCreatePlanRequest {
    /**
     * Your unique ID for the plan
     * @type {string}
     * @memberof SourceCreatePlanRequest
     */
    'oid': string;
    /**
     * Your internal name for this plan. This will be displayed in the Plan Breakout section
     * @type {string}
     * @memberof SourceCreatePlanRequest
     */
    'name': string;
    /**
     * The ISO code of the currency of this plan. E.G: usd
     * @type {string}
     * @memberof SourceCreatePlanRequest
     */
    'currency': string;
    /**
     * How much is this plan? (In cents)
     * @type {number}
     * @memberof SourceCreatePlanRequest
     */
    'amount': number;
    /**
     * day, month or year
     * @type {string}
     * @memberof SourceCreatePlanRequest
     */
    'interval': string;
    /**
     * 
     * @type {number}
     * @memberof SourceCreatePlanRequest
     */
    'interval_count': number;
    /**
     * The duration of this trial. This is to be used in conjunction with trial_duration_unit
     * @type {number}
     * @memberof SourceCreatePlanRequest
     */
    'trial_duration'?: number;
    /**
     * This is to be used in conjunction with trial_duration
     * @type {string}
     * @memberof SourceCreatePlanRequest
     */
    'trial_duration_unit'?: string;
}

