/*
Production

Baremetrics provides real-time subscription metrics for teams built with Stripe, Shopify Partners, Braintree, Recurly, Chargebee, Google Play, and App Store Connect. 

In addition to metrics, Baremetrics provides tools that help you reduce churn and grow your business faster: 

Recover: Prevent failed charges and keep your hard-earned revenue with our 100% automated toolkit. 

Cancellation insights: Learn exactly why your customers cancel, calculate lost revenue by cancellation reason, and send automated emails to win customers back.

Flightpath: Plan for the future with flexible financial modeling tools built for growing SaaS companies.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SourceCreatePlanResponsePlanAmountsInner } from './source-create-plan-response-plan-amounts-inner';

/**
 * 
 * @export
 * @interface SourceCreatePlanResponsePlan
 */
export interface SourceCreatePlanResponsePlan {
    /**
     * 
     * @type {string}
     * @memberof SourceCreatePlanResponsePlan
     */
    'oid'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreatePlanResponsePlan
     */
    'source_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreatePlanResponsePlan
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreatePlanResponsePlan
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceCreatePlanResponsePlan
     */
    'interval'?: string;
    /**
     * 
     * @type {number}
     * @memberof SourceCreatePlanResponsePlan
     */
    'interval_count'?: number;
    /**
     * 
     * @type {any}
     * @memberof SourceCreatePlanResponsePlan
     */
    'trial_duration'?: any;
    /**
     * 
     * @type {any}
     * @memberof SourceCreatePlanResponsePlan
     */
    'trial_duration_unit'?: any;
    /**
     * 
     * @type {any}
     * @memberof SourceCreatePlanResponsePlan
     */
    'created'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof SourceCreatePlanResponsePlan
     */
    'active'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SourceCreatePlanResponsePlan
     */
    'setup_fees'?: number;
    /**
     * 
     * @type {Array<SourceCreatePlanResponsePlanAmountsInner>}
     * @memberof SourceCreatePlanResponsePlan
     */
    'amounts'?: Array<SourceCreatePlanResponsePlanAmountsInner>;
}

